#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# start_reth.sh — Start Reth in dev mode with generated genesis
# ═══════════════════════════════════════════════════════════════
# Replaces Anvil for long-running persistent testnet usage.
# Uses MDBX disk-backed storage instead of in-memory state.
#
# Prerequisites:
#   - reth binary in PATH
#   - genesis.json generated by convert_state.py
#
# Usage:
#   ./start_reth.sh                    # Start in foreground
#   ./start_reth.sh --background       # Start in background
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RLD_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

# ─── Configuration ────────────────────────────────────────────
GENESIS="${SCRIPT_DIR}/genesis.json"
DATADIR="${RETH_DATADIR:-$HOME/.local/share/reth-dev}"
HOST="${RETH_HOST:-0.0.0.0}"
PORT="${RETH_PORT:-8545}"
BLOCK_TIME="${RETH_BLOCK_TIME:-1}"
LOG_FILE="${RETH_LOG:-/tmp/reth.log}"
BACKGROUND=false

for arg in "$@"; do
    case "$arg" in
        --background|-b) BACKGROUND=true ;;
        --help|-h)
            echo "Usage: $0 [--background]"
            echo "  --background   Start Reth in background (logs to $LOG_FILE)"
            exit 0
            ;;
    esac
done

# ─── Preflight ────────────────────────────────────────────────
if ! command -v reth &>/dev/null; then
    echo "❌ reth not found in PATH"
    echo "   Install: curl -L https://paradigmxyz.github.io/reth/installation/installation.html"
    echo "   Or: cargo install --locked reth"
    exit 1
fi

if [ ! -f "$GENESIS" ]; then
    echo "❌ Genesis file not found at $GENESIS"
    echo "   Run 00_warmup.sh first to generate it"
    exit 1
fi

# Create datadir
mkdir -p "$DATADIR"

ACCOUNT_COUNT=$(python3 -c "import json; print(len(json.load(open('$GENESIS'))['alloc']))" 2>/dev/null || echo "?")
echo "═══════════════════════════════════════════════════"
echo "🦀 Starting Reth Dev Node"
echo "═══════════════════════════════════════════════════"
echo "  Genesis:    $GENESIS ($ACCOUNT_COUNT accounts)"
echo "  Datadir:    $DATADIR"
echo "  RPC:        http://${HOST}:${PORT}"
echo "  Block time: ${BLOCK_TIME}s"
echo "  Background: $BACKGROUND"
echo "═══════════════════════════════════════════════════"

RETH_CMD=(
    reth node
    --dev
    --dev.block-time "${BLOCK_TIME}s"
    --chain "$GENESIS"
    --datadir "$DATADIR"
    --http
    --http.addr "$HOST"
    --http.port "$PORT"
    --http.api "eth,net,web3,debug,trace,txpool"
    --http.corsdomain "*"
    --gpo.maxprice 1000000
    --log.stdout.filter "info"
)

if [ "$BACKGROUND" = true ]; then
    echo "  Log file:   $LOG_FILE"
    nohup "${RETH_CMD[@]}" > "$LOG_FILE" 2>&1 &
    RETH_PID=$!
    echo "  PID:        $RETH_PID"
    echo ""

    # Wait for Reth to be ready
    echo "⏳ Waiting for Reth to respond..."
    for i in $(seq 1 60); do
        if cast block-number --rpc-url "http://localhost:${PORT}" > /dev/null 2>&1; then
            BLOCK=$(cast block-number --rpc-url "http://localhost:${PORT}")
            echo "✅ Reth ready at block $BLOCK (took ${i}s)"
            break
        fi
        if [ $((i % 10)) -eq 0 ]; then
            echo "   Still waiting... (${i}/60s)"
        fi
        sleep 1
    done

    if ! cast block-number --rpc-url "http://localhost:${PORT}" > /dev/null 2>&1; then
        echo "❌ Reth failed to start after 60s"
        echo "Last 20 lines of $LOG_FILE:"
        tail -20 "$LOG_FILE" 2>/dev/null || true
        exit 1
    fi
else
    exec "${RETH_CMD[@]}"
fi
